#!/bin/bash

function make () {
	el=$1[@]
	elar=("${!el}")
	for  i in "${elar[@]}"
	do
		name=$(echo "$i" | sed "s/\.gabc//")
		text="${text}${name}\n\gregorioscore{${name}}\n"
	done
}

function calculate () {

	text="\documentclass[12pt, a5paper]{article}
\usepackage{fullpage}
\usepackage{fontspec}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\\\begin{document}
"
	day="$1"
	text="${text}${day}\n"
	text="${text}Prima\n"
	#should I include the monastic one?
	case "$1" in
	"Feria Secunda")
		p1=($(ls 23-*.gabc))
		p2=($(ls 18-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p=($(ls 24-*.gabc))
		make p
	;;
	"Feria Quarta")
		p1=($(ls 25-*.gabc))
		p2=($(ls 51-*.gabc))
		p3=($(ls 52-*.gabc))
		p1=(${p1[@]} ${p2[@]} ${p3[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 22-*.gabc))
		p2=($(ls 71-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Sexta")
		p=($(ls 21-*.gabc))
		make p
	;;
	"Sabbato")
		p1=($(ls 93-*.gabc))
		p2=($(ls 107-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Dominica")
		p1=($(ls 117-*.gabc))
		p2=($(ls 118-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	esac
	text="${text}Tertia\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 26-*.gabc))
		p2=($(ls 27-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p=($(ls 39-*.gabc))
		make p
	;;
	"Feria Quarta")
		p1=($(ls 53-*.gabc))
		p2=($(ls 54-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 72-*.gabc))
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 79-*.gabc))
		p2=($(ls 81-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Sabbato")
		p1=($(ls 101-*.gabc))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc))
		#make p1
	;;
	esac
	text="${text}Sexta\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 30-*.gabc))
		make p1
	;;
	"Feria Tertia")
		p1=($(ls 40-*.gabc))
		p2=($(ls 41-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quarta")
		p1=($(ls 55-*.gabc))
		p2=($(ls 56-*.gabc))
		p3=($(ls 57-*.gabc))
		p1=(${p1[@]} ${p2[@]} ${p3[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 73-*.gabc))
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 83-*.gabc))
		p2=($(ls 86-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Sabbato")
		p1=($(ls 103-*.gabc))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc))
		#make p1
	;;
	esac
	text="${text}Nona\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 31-*.gabc))
		p2=($(ls 32-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p1=($(ls 43-*.gabc))
		make p1
	;;
	"Feria Quarta")
		p1=($(ls 58-*.gabc))
		p2=($(ls 59-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 74-*.gabc))
		p2=($(ls 75-*.gabc))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 88-*.gabc))
		make p1
	;;
	"Sabbato")
		p1=($(ls 108-*.gabc))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc))
		#make p1
	;;
	esac
	text="${text}\\\end{document}"

	echo -e "$text"

}

days=("Feria Secunda" "Feria Tertia" "Feria Quarta" "Feria Quinta" "Feria Sexta" "Sabbato" "Dominica")
for i in "${days[@]}"
do
	calculate "$i"
done

