#!/bin/bash

function make () {
	el=$1[@]
	elar=("${!el}")
	for  i in "${elar[@]}"
	do
		name=$(echo "$i" | sed "s/\.gabc//")
		text="${text}${name}\n\gregorioscore{${name}}\n"
	done
}

function calculate () {

	text="\documentclass[12pt, a5paper]{article}
\usepackage{fullpage}
\usepackage{fontspec}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\\\begin{document}
"
	day="$1"
	text="${text}${day}\n"
	text="${text}Prima\n\n"
	#should I include the monastic ones?
	case "$1" in
	"Feria Secunda")
		p1=($(ls 23-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 18-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p=($(ls 24-*.gabc | grep -v "antiquo\|monasticus"))
		make p
	;;
	"Feria Quarta")
		p1=($(ls 25-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 51-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 52-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 22-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 71-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Sexta")
		p=($(ls 21-*.gabc | grep -v "antiquo\|monasticus"))
		make p
	;;
	"Sabbato")
		p1=($(ls 93-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 107-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Dominica")
		p1=($(ls 117-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 118-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	esac
	text="${text}Tertia\n\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 26-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 27-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p=($(ls 39-*.gabc | grep -v "antiquo\|monasticus"))
		make p
	;;
		"Feria Quarta")
		p1=($(ls 53-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 54-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 72-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 79-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 81-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Sabbato")
		p1=($(ls 101-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc | grep -v "antiquo\|monasticus"))
		#make p1
	;;
	esac
	text="${text}Sexta\n\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 30-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Feria Tertia")
		p1=($(ls 40-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 41-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quarta")
		p1=($(ls 55-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 56-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 57-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 73-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 83-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 86-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Sabbato")
		p1=($(ls 103-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc | grep -v "antiquo\|monasticus"))
		#make p1
	;;
	esac
	text="${text}Nona\n\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 31-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 32-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Tertia")
		p1=($(ls 43-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Feria Quarta")
		p1=($(ls 58-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 59-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 74-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 75-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 88-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Sabbato")
		p1=($(ls 108-*.gabc | grep -v "antiquo\|monasticus"))
		make p1
	;;
	"Dominica")
		#p1=($(ls 118-*.gabc | grep -v "antiquo\|monasticus"))
		#make p1
	;;
	esac
	text="${text}Vesperae\n\n"
	case "$1" in
	"Feria Secunda")
		p1=($(ls 114-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 115-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 119-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 120-*.gabc | grep -v "antiquo\|monasticus"))
		p5=($(ls 121-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]} ${p5[@]})
		make p1
	;;
	"Feria Tertia")
		p1=($(ls 122-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 123-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 124-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 125-*.gabc | grep -v "antiquo\|monasticus"))
		p5=($(ls 126-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]} ${p5[@]})
		make p1
	;;
	"Feria Quarta")
		p1=($(ls 127-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 128-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 129-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 130-*.gabc | grep -v "antiquo\|monasticus"))
		p5=($(ls 131-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]} ${p5[@]})
		make p1
	;;
	"Feria Quinta")
		p1=($(ls 132-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 135-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 136-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 137-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]})
		make p1
	;;
	"Feria Sexta")
		p1=($(ls 138-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 139-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 140-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 141-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]})
		make p1
	;;
	"Sabbato")
		p1=($(ls 143-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 144-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]})
		make p1
	;;
	"Dominica")
		p1=($(ls 109-*.gabc | grep -v "antiquo\|monasticus"))
		p2=($(ls 110-*.gabc | grep -v "antiquo\|monasticus"))
		p3=($(ls 111-*.gabc | grep -v "antiquo\|monasticus"))
		p4=($(ls 112-*.gabc | grep -v "antiquo\|monasticus"))
		p5=($(ls 113-*.gabc | grep -v "antiquo\|monasticus"))
		p1=(${p1[@]} ${p2[@]} ${p3[@]} ${p4[@]} ${p5[@]})
		make p1
	;;
	esac
	text="${text}\\\end{document}"

	echo -e "$text"

}

days=("Feria Secunda" "Feria Tertia" "Feria Quarta" "Feria Quinta" "Feria Sexta" "Sabbato" "Dominica")
for i in "${days[@]}"
do
	res=$(calculate "$i")
	name=$(echo "$i" | sed "s/ /_/")
	echo "$res" > "${name}.tex"
done

